version: "3"
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    restart: always
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms128M -Xmx256M
    depends_on:
      - kafka

  postgres:
    build: ./postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_data

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    restart: always
    container_name: elastic
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data01

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    depends_on:
      - elastic

  connect:
    image: debezium/connect-jdbc-es:${DEBEZIUM_VERSION}
    restart: always
    build:
      context: debezium-synch
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - postgres
      - elastic
      - kibana
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=pg_es_synch_configs
      - OFFSET_STORAGE_TOPIC=pg_es_synch_offsets
      - STATUS_STORAGE_TOPIC=pg_es_synch_connect_statuses

volumes:
  elasticsearch-data:
    driver: local
